// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2PexlB8NFtwPxsP6d1S5nI1V9aGNIY2c',
    appId: '1:198879506519:web:337e09119dfbea6407f312',
    messagingSenderId: '198879506519',
    projectId: 'kishoutenketsu-rta',
    authDomain: 'kishoutenketsu-rta.firebaseapp.com',
    storageBucket: 'kishoutenketsu-rta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk29a-aga2VNk3gfS88yHOicqEWnvXUu8',
    appId: '1:198879506519:android:50baf23c864d128907f312',
    messagingSenderId: '198879506519',
    projectId: 'kishoutenketsu-rta',
    storageBucket: 'kishoutenketsu-rta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCogb8a_mUW1VV7TzSvWupwwgKQig4BTCg',
    appId: '1:198879506519:ios:4131b9d44ab1e1d307f312',
    messagingSenderId: '198879506519',
    projectId: 'kishoutenketsu-rta',
    storageBucket: 'kishoutenketsu-rta.appspot.com',
    iosClientId:
        '198879506519-kabkora1jf0m1uhadcn94121o9id8hcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.kishoutenketsuRta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCogb8a_mUW1VV7TzSvWupwwgKQig4BTCg',
    appId: '1:198879506519:ios:4131b9d44ab1e1d307f312',
    messagingSenderId: '198879506519',
    projectId: 'kishoutenketsu-rta',
    storageBucket: 'kishoutenketsu-rta.appspot.com',
    iosClientId:
        '198879506519-kabkora1jf0m1uhadcn94121o9id8hcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.kishoutenketsuRta',
  );
}
